### PR TITLE
Remove `setup-x86_64.exe` after it is used

### PR DESCRIPTION
**Pull request by wilfwilson**
Having this file still around is a minor annoyance in some other stuff that I'm doing, so if you don't mind I'd like it to be deleted after its use.

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Seems sensible to me. The one drawback is (AFAIK, I might be wrong) that one then cannot easily install further cygwin packages using it later on. But ideally that shouldn't be necessary anyway?

**Comment by wilfwilson** [comment]
Actually I'm not even sure that `cmd` supports `rm -f` (as opposed to just `rm`) so I might need to change this. In any case I've now avoided that minor annoyance, so I'm not really bothered about this PR any more. Might just close it!

**Comment by ssiccha** [comment]
I'm closing it then.

**Comment by wilfwilson** [comment]
Thanks @ssiccha - I'd decided to close, thanks 🙂

**Pull request closed without merging**
